### ISSUE TITLE
twitch is showing this before every stream and buffering even on gigabit internet. 

### ISSUE THREAD

**Issue by spamsgood** [Aayush9029/NativeTwitch#21]
<img width="825" alt="IMG_2393" src="https://user-images.githubusercontent.com/28077404/143668009-d5a7252f-4bd4-495e-a8f7-c8d80b96e130.png">

When I access through the web browser it seems to work fine, but when accessed through native twitch it is buffering even with gigabit ethernet internet. It seems like twitch has started artificially limiting the bandwidth. This is outside your control I understand. This is more of a "FYI" that ive started getting this.

**Comment by Aayush9029** [comment]
The message is fine, twitch embeds  that sometimes. But I highly doubt they're limiting bandwidth.

Here I opened a stream to test.
The buffer is healthy *look at iina*

*QuickTime image*
![Screen Shot 2021-11-27 at 10 22 53 AM](https://user-images.githubusercontent.com/43297314/143687206-9a67fc0f-26b2-49b5-bac1-20db8ebdefea.png)

*iina image*
![Screen Shot 2021-11-27 at 10 23 27 AM](https://user-images.githubusercontent.com/43297314/143687209-bc53fabe-bbce-4bfb-8192-390b5a072b3a.png)


---
I even tried using cellular hotspot *to throttle the speed* and it works fine.
Have you tried using different connection different IP?

**Comment by Aayush9029** [comment]
You can try my new build that has been "released"

It uses embedded streamlink.
It's not notarized so you'll have to right click and or use xattr -c 

Hopefully that works!
