### ISSUE TITLE
Native Twitch can't open stream where its channel name contains with Chinese characters

### ISSUE THREAD

**Issue by detecti1914** [Aayush9029/NativeTwitch#25]
NativeTwitch Version: Latest (1.6)
IINA Version: 1.2.0

Native Twitch can't open stream where its channel name contains with Chinese characters. For example, this channel with Chinese channel name   https://www.twitch.tv/meidingdang126

<img width="1389" alt="Screen Shot 2022-04-17 at 23 38 08" src="https://user-images.githubusercontent.com/211184/163721715-2a6a5295-59e3-44fc-be98-ea50e2870770.png">

<img width="432" alt="Screen Shot 2022-04-17 at 23 45 37" src="https://user-images.githubusercontent.com/211184/163721944-3471992e-96e2-4ec4-b537-0c4009619d59.png">

**Comment by detecti1914** [comment]
By the way, I can open the same channel stream directly in Terminal with streamline command.

<img width="656" alt="Screen Shot 2022-04-17 at 23 47 15" src="https://user-images.githubusercontent.com/211184/163722016-806ea26e-5eee-470a-a107-d20d85e78fec.png">

**Comment by Aayush9029** [comment]
@detecti1914 Great find!

What was the log for NativeTwitch? 
> (Command + ,) show logs, copy logs. (Hide token) 


Feel free to send me the twitch channel's with similar names!

**Comment by detecti1914** [comment]
Here is my log (Other channel work fine, like the third one)

`2022-04-18 00:39:02 +0000 | User Validated
2022-04-18 00:39:02 +0000 | User Validated
response: {
  "login" : "*******USERNAME********",
  "scopes" : [
    "user:read:follows"
  ],
  "client_id" : "********CLIENTID*****",
  "expires_in" : 0,
  "user_id" : "*******USER_ID********"
}

2022-04-18 00:39:02 +0000 | User Validated
response: {
  "login" : "*******USERNAME********",
  "scopes" : [
    "user:read:follows"
  ],
  "client_id" : "********CLIENTID*****",
  "expires_in" : 0,
  "user_id" : "*******USER_ID********"
}

2022-04-18 00:39:02 +0000 | Current version is the latest version ✅
2022-04-18 00:39:03 +0000 | Stream Has Been Loaded
response: {
  "pagination" : {

  },
  "data" : [
    {
      "is_mature" : true,
      "thumbnail_url" : "https:\/\/static-cdn.jtvnw.net\/previews-ttv\/live_user_meidingdang126-{width}x{height}.jpg",
      "user_id" : "771791898",
      "game_id" : "509658",
      "user_login" : "meidingdang126",
      "started_at" : "2022-04-17T15:41:06Z",
      "title" : "《美叮噹》小朋友坐好，準備上課，今天看電影。｜台灣夜市｜泳池大王｜交通安全｜迷因｜按摩俱樂部",
      "language" : "zh",
      "id" : "40726992283",
      "tag_ids" : [
        "74c92063-a389-4fd2-8460-b1bb82b04ec7"
      ],
      "game_name" : "Just Chatting",
      "viewer_count" : 374,
      "user_name" : "水桶大霸誰修哈",
      "type" : "live"
    },
    {
      "is_mature" : false,
      "thumbnail_url" : "https:\/\/static-cdn.jtvnw.net\/previews-ttv\/live_user_kinganime102-{width}x{height}.jpg",
      "user_id" : "714925160",
      "game_id" : "518203",
      "user_login" : "kinganime102",
      "started_at" : "2022-04-17T03:25:42Z",
      "title" : "24小時回顧那些年來被遺忘的經典與糞作，請務必加入DC追蹤開台跟片單",
      "language" : "zh",
      "id" : "46193454637",
      "tag_ids" : [
        "74c92063-a389-4fd2-8460-b1bb82b04ec7"
      ],
      "game_name" : "Sports",
      "viewer_count" : 118,
      "user_name" : "請問您今天要來點アニメ嗎",
      "type" : "live"
    },
    {
      "is_mature" : true,
      "thumbnail_url" : "https:\/\/static-cdn.jtvnw.net\/previews-ttv\/live_user_akb48_taiwan_clubs-{width}x{height}.jpg",
      "user_id" : "703873435",
      "game_id" : "",
      "user_login" : "akb48_taiwan_clubs",
      "started_at" : "2022-04-17T22:36:58Z",
      "title" : "AKB48-Taiwan Clubs LIVE CHANNEL",
      "language" : "ja",
      "id" : "46199756381",
      "tag_ids" : [
        "6ba1d230-e52f-4d81-b1e0-41f25a8a9f5d"
      ],
      "game_name" : "",
      "viewer_count" : 34,
      "user_name" : "akb48_taiwan_clubs",
      "type" : "live"
    }
  ]
}

2022-04-18 00:39:37 +0000 | Stream Has Been Loaded
response: The files /No, /playable, /streams, /found, /on, /this, and /twitch.tv/水桶大霸誰修哈 do not exist.


2022-04-18 00:39:37 +0000 | Stream Has Been Loaded
response: BIG FAIL 😩 @ /opt/homebrew/bin/streamlink

2022-04-18 00:39:37 +0000 | Stream Has Been Loaded
response: streamlink not found


2022-04-18 00:41:02 +0000 | Stream Has Been Loaded
response: /opt/homebrew/bin/streamlink:🎉 Success 🎉

`

**Comment by detecti1914** [comment]
I wonder if we can use "user_login" instead of "username" as the url parameter, for I can successfully load stream with this command in the picture below

<img width="656" alt="163722016-806ea26e-5eee-470a-a107-d20d85e78fec" src="https://user-images.githubusercontent.com/211184/163738873-7393952e-56db-46a2-9001-d504d99b2d73.png">

<img width="831" alt="Screen Shot 2022-04-18 at 08 51 53" src="https://user-images.githubusercontent.com/211184/163738877-c0b55cb9-6d59-457e-a0a2-918ece39ad36.png">

**Comment by Aayush9029** [comment]
Fixed

**Comment by Aayush9029** [comment]
@detecti1914 

You can download it [here](https://github.com/Aayush9029/NativeTwitch/releases/download/v5.1.6.1/NativeTwitch.app.zip) I'll release it (auto-update) next month with major changes :D

I didn't take time to notarize it, I've only changed few lines.

Thanks for pointing "user_name" out
