### ISSUE TITLE
[Feature] Manually set quality

### ISSUE THREAD

**Issue by nedex** [Aayush9029/NativeTwitch#27]
Hello,
I was wondering if there could be a way to manually pick quality settings.
I've been modifying the default streamlink configuration file but I saw in the code that apparently the "best" quality is always picked, overriding user's choices.

https://github.com/Aayush9029/NativeTwitch/blob/2d32e7ba2b0bab90b83fe925ca886d0e71de2073/NativeTwitch/View%20Model/TwitchDataViewModel.swift#L153

Maybe in the settings a dropdown menu would be more user-friendly.

Thanks anyways.

**Comment by Aayush9029** [comment]
@nedex Done 🎉  #29
