### ISSUE TITLE
🐞BUG: Stream doesn't open

### ISSUE THREAD

**Issue by jasmanchik** [Aayush9029/NativeTwitch#38]
When i try to open a stream through IINA player nothing happens exept welcome screen IINA's player. How to fix that? 
If i try to open without IINA player, welcome screen QuickTime player opens too and that's all.

<img width="332" alt="image" src="https://user-images.githubusercontent.com/40543800/223625044-a500cd25-9c56-4b7f-a29b-6e030de57e67.png">

**Logs:**
`BF0C2CAF-A5E6-455B-AE6C-CE362B697AC3 : 2023-03-08 05:15:25 +0000 >> Loading Streams
 F4F5A501-B503-46A9-87A9-60CD49916465 : 2023-03-08 05:15:25 +0000 >> Streams Loaded
 C504D431-2D3A-4052-9804-B7A0DA3CC740 : 2023-03-08 05:15:25 +0000 >> {
  "pagination" : {},
  "data" : [
    {
      "game_name" : "Just Chatting",
      "is_mature" : false,
      "thumbnail_url" : "https:\/\/static-cdn.jtvnw.net\/previews-ttv\/live_user_xqc-{width}x{height}.jpg",
      "language" : "en",
      "user_name" : "xQc",
      "type" : "live",
      "id" : "41934353691",
      "game_id" : "509658",
      "user_login" : "xqc",
      "tag_ids" : [],
      "title" : "💀LIVE FROM THE OFFICE💀MEGA DRAMA💀CLICK💀CATCHING UP WITH CHAT💀WICKED💀CLICK HERE💀RIZZMASTER💀LORD💀WICKED INSANE💀#1 CHAMPION💀HERE💀",
      "user_id" : "71092938",
      "viewer_count" : 59713,
      "tags" : [
        "English",
        "vtuber",
        "depression",
        "adhd",
        "psychosis",
        "xqc",
        "femboy",
        "anime",
        "reaction",
        "IRL"
      ],
      "started_at" : "2023-03-08T01:38:36Z"
    },
    {
      "game_name" : "Just Chatting",
      "user_name" : "FilmsHere",
      "title" : "МАРАФОН ФИЛЬМОВ ДЛЯ ДАМ! С 8 марта! !фильм !праздник",
      "is_mature" : false,
      "tag_ids" : [],
      "id" : "40545667592",
      "user_login" : "filmshere",
      "viewer_count" : 229,
      "type" : "live",
      "language" : "ru",
      "game_id" : "509658",
      "thumbnail_url" : "https:\/\/static-cdn.jtvnw.net\/previews-ttv\/live_user_filmshere-{width}x{height}.jpg",
      "tags" : [
        "фильм",
        "фильмы",
        "кино",
        "марафон",
        "Русский"
      ],
      "started_at" : "2023-03-08T05:03:32Z",
      "user_id" : "873424780"
    }
  ]
}`

Welcome screen IINA:
<img width="632" alt="image" src="https://user-images.githubusercontent.com/40543800/223625425-c00b5627-9b00-4032-91f7-3170e0c38004.png">

**Comment by Aayush9029** [comment]
@jasmanchik 

What's the output for `which streamlink`



Run in terminal

**Comment by jasmanchik** [comment]
<img width="229" alt="image" src="https://user-images.githubusercontent.com/40543800/223627614-71d9f907-87bf-4653-8b09-b3e2d8563ce8.png">

**Comment by Aayush9029** [comment]
Ok I'll take a look at it :) 

Thanks a lot for letting me know

**Comment by Aayush9029** [comment]
😉 Updates: https://github.com/Aayush9029/NativeTwitch/tree/v3

👋 Bye stream-link altogether (optional).

**Comment by Aayush9029** [comment]
@jasmanchik 

Update: Before v3 releases, IINA natively supports twitch now.

`iina://open?url=https://www.twitch.tv/channel_name`
