### ISSUE TITLE
Opens QuickTime player even if streamlink is installed 

### ISSUE THREAD

**Issue by Horiology** [Aayush9029/NativeTwitch#4]
Streamlink is already installed via homebrew, however right clicking on the stream opens QuickTime Player as opposed to streamlinked. I checked and the file location is correctly pointing to the folder. macOS Big Sur 11.5.2.

**Comment by Aayush9029** [comment]
Interesting.
Could you tell me..
what's the output for 
``` which streamlink```
What Mac are you using (M1 or intel) and what macOS version are you running.

*I'll look into adding a debug log for streamlink path soon, prob next week, hopefully it'll help?*

**Comment by unbeatable-101** [comment]
Same thing is happening to me, I have an M1 Mac and `which streamlink` outputs `/opt/homebrew/bin/streamlink` which is the same as what is in settings.

**Comment by Horiology** [comment]
Intel based mac, macOS Big Sur 11.5.2.
which streamlink outputs as `/usr/local/bin/streamlink` (which is the same location I set in preferences)

**Comment by Aayush9029** [comment]
I updated the app, now it should show streamlink shell logs.
I'll prob add a way to export logs soon so you don't have to take a screen shot.

Anyways feel free to check: https://github.com/Aayush9029/NativeTwitch/releases/tag/v0.30 I've posted some info there.

*This might help me debug the problem :)*

**Comment by unbeatable-101** [comment]
@Horiology This isn't a bug, Streamlink is just used to get the stream link

**Comment by Horiology** [comment]
As of release v0.30, this correctly works now. QuickTime opens as expected, and shows the stream as opposed to just opening without showing the stream.

**Comment by Aayush9029** [comment]
> ~Same thing is happening to me, I have an M1 Mac and `which streamlink` outputs `/opt/homebrew/bin/streamlink` which is the same as what is in settings.~ I'm Dumb

I’m a little confused 🤔 
Was your path wrong?

**Comment by unbeatable-101** [comment]
I was tired last night and saw the person saying the stream was opening in quicktime instead of streamlink, so I just said "same here" without looking into what streamlink actually was.
