### ISSUE TITLE
CPU usage in background

### ISSUE THREAD

**Issue by jobukkit** [Aayush9029/NativeTwitch#40]
NativeTwitch is constantly using 10%-20% CPU in the background now. Maybe this is a Sonoma-specific issue?

<img width="481" alt="Scherm­afbeelding 2023-12-12 om 18 04 17" src="https://github.com/Aayush9029/NativeTwitch/assets/2750434/70a2fd50-d1e8-4b7f-9e6c-a6a595fd0621">

**Comment by Aayush9029** [comment]
Can confirm this is happening in Sonoma will take a look later this week.

**Comment by Aayush9029** [comment]
https://github.com/Aayush9029/NativeTwitch/tree/v4

**Comment by Aayush9029** [comment]
![CleanShot 2023-12-16 at 12 19 03@2x](https://github.com/Aayush9029/NativeTwitch/assets/43297314/959b3f15-eb75-42fc-9cc6-d2877c59b135)

Issue has been resolved in v4. 

- Update: NativeTwitch uses 0% (almost no) cpu when in background. Cheers!

**Comment by Aayush9029** [comment]
Will push the optimized release later tomorrow for you to test.

**Comment by jobukkit** [comment]
Thanks for your work!
